server:
  port: 8000
  servlet:
    session:
      cookie:
        name: SESSIONID
    context-path: /sso
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.255.184:3306/yhuk_power?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: aca1b7dd6d4ed58e320288fbb343240b